# Adapted from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
# cache:
#   directories:
#     - $HOME/.cache/pip
#     - $HOME/miniconda

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  # - "3.6"

install:
  - sudo apt-get update
  - sed 's/#.*//' Aptfile | xargs sudo apt-get install

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # https://stackoverflow.com/a/38609653
  - while read reqpkg; do conda install --yes $reqpkg || pip install $reqpkg; done < requirements_worker.txt
  - while read reqpkg; do conda install --yes $reqpkg || pip install $reqpkg; done < requirements.txt

  # Install this code
  - pip install -e .

script:
  - py.test -v --color=yes --exitfirst --showlocals
  - codecov
